import { IAM_ACTIONS } from "../../shared/iam-action";

export const IOT_ACTION = {
  CONNECTIVITY_ACTIONS: [
    ...IAM_ACTIONS.DYNAMODB_LAMBDA_EXEC_ACCESS,
    ...IAM_ACTIONS.DYNAMODB_READ_WRITE_ACCESS,
    ...IAM_ACTIONS.IOT_DATA_ACCESS,
    ...IAM_ACTIONS.APPSYNC_INVOKE_FULL_ACCESS,
    ...IAM_ACTIONS.SNS_FULL_ACCESS
  ],
  LIGHT_ACTIONS: [
    ...IAM_ACTIONS.DYNAMODB_READ_WRITE_ACCESS
  ],
  BATTERY_ACTIONS: [
    ...IAM_ACTIONS.DYNAMODB_READ_WRITE_ACCESS,
    ...IAM_ACTIONS.SNS_FULL_ACCESS
  ],
  FIRMWARE_ACTIONS: [
    ...IAM_ACTIONS.DYNAMODB_READ_WRITE_ACCESS
  ],
  MOTOR_RESPONSE_ACTIONS: [
    ...IAM_ACTIONS.APPSYNC_INVOKE_FULL_ACCESS,
  ]

};